# Site settings
title: 0xBU
description: Boston University CTF Team
baseurl: ""
url: "https://0xbu.github.io"
twitter_username: 0xbu
github_username:  0xbu

# Build settings
remote_theme: daattali/beautiful-jekyll
markdown: kramdown
permalink: /blog/:title/
google_analytics: UA-0000000-1
highlighter: rouge

plugins:
  - jekyll-sitemap
